CREATE DATABASE IF NOT EXISTS `db-account`;
CREATE DATABASE IF NOT EXISTS `db-participant`;
CREATE DATABASE IF NOT EXISTS `db-company`;
CREATE DATABASE IF NOT EXISTS `db-management-content`;
CREATE DATABASE IF NOT EXISTS `db-mapping`;
CREATE DATABASE IF NOT EXISTS `db-grade`;
