FROM node:16-alpine

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

COPY package*.json ./

RUN apk add --no-cache python3 make g++

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
